name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Pipeline berjalan saat ada perubahan di branch 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan pipeline di server Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Mengambil kode dari repository

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # Versi Python yang akan digunakan

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Menginstal dependensi proyek

      - name: Run tests
        run: |
          pytest  # Menjalankan pengujian. Gantilah dengan perintah testing proyekmu

